### ISSUE TITLE
Add graph of LP token price to TFUEL price ratio 

### ISSUE THREAD

**Issue by davidbindel** [czmathew/TBillStakingDashboard#101]
I would like to be able to view a graph of historical ratios of LP token price over TFUEL price. This provides some idea of the value retained in an investment into the LP versus just holding TFUEL.

**Comment by czmathew** [comment]
would something like this work?
![image](https://user-images.githubusercontent.com/2764131/185999620-97d4b86f-078d-42ab-9b3b-543543154c74.png)

**Comment by davidbindel** [comment]
Yes, that's what I'm interested in.

Would also be interesting to have a graph that shows the present TFuel value of 1 LP token + the present TFuel value of its cumulative rewards over time (from a specified start date) with a specified multiplier (2x, etc.) in effect.

**Comment by czmathew** [comment]
the LP token / TFuel chart has been added.
I'm not sure I understand the other requirement, but let's keep that in a separate issue if it should be done. Thanks
