### ISSUE TITLE
Who is purchasing the NFTs? One wallet?

### ISSUE THREAD

**Issue by Edyxia** [czmathew/TBillStakingDashboard#14]
Maybe we can track whales wallet on a different page?

**Comment by czmathew** [comment]
We can add a list with last 10/20/50 NTF sales with some additional details like first 10 characters from the wallet addresses. That will be enough to see if it's the same address for the purchases. Not sure if we would go with complete address

**Comment by Edyxia** [comment]
This solution is perfect. Let's keep the whole address private though and people can investigate on their own!

**Comment by czmathew** [comment]
fixed and deployed
