### ISSUE TITLE
Add TBILL gained for the current day and total TBILL rewards from a wallet

### ISSUE THREAD

**Issue by Edyxia** [czmathew/TBillStakingDashboard#23]
<img width="692" alt="CleanShot 2022-03-22 at 21 41 29@2x" src="https://user-images.githubusercontent.com/79707346/159572139-9411abd7-600f-4a57-ab54-2af3ce8d9048.png">

<img width="574" alt="CleanShot 2022-03-22 at 21 41 37@2x" src="https://user-images.githubusercontent.com/79707346/159572154-8c54a134-0187-4ea5-9e3f-1f101fb2cd69.png">

**Comment by czmathew** [comment]
done and done in the next release
