### ISSUE TITLE
Add wallet TFuel & TBill balance, also total TBill rewards 

### ISSUE THREAD

**Issue by czmathew** [czmathew/TBillStakingDashboard#24]

**Comment by czmathew** [comment]
@Edyxia is this balance in LP or in the wallet?

**Comment by Edyxia** [comment]
Maybe it was something like this. So we show the current one on top, the latest one. And not only the history?

![CleanShot 2022-03-25 at 22 00 04@2x](https://user-images.githubusercontent.com/79707346/160200141-b1f8bf54-a187-4451-b652-f4fb1fb629a4.png)

**Comment by czmathew** [comment]
the balance will be taken from daily rewards history
