### ISSUE TITLE
[Quick Fix] Tfuel and Tbill labels interchanged

### ISSUE THREAD

**Issue by Edyxia** [czmathew/TBillStakingDashboard#4]
The Tfuel and Tbill labels are interchanged. 1 needs to be 2 and the other way around.

![CleanShot 2022-03-20 at 14 59 35@2x](https://user-images.githubusercontent.com/79707346/159166072-68f2a9cb-74f8-4e8c-9efd-0cca617bcd01.png)

**Comment by czmathew** [comment]
fixed and deployed
