### ISSUE TITLE
Labeling The Price

### ISSUE THREAD

**Issue by Edyxia** [czmathew/TBillStakingDashboard#5]
Explain or change the label here to LastSold?
Add somewhere that the price is in Tfuel, not dollars

![CleanShot 2022-03-20 at 15 07 59@2x](https://user-images.githubusercontent.com/79707346/159166493-f0f126bf-4f2a-4e7b-b0b5-76136c256901.png)

**Comment by czmathew** [comment]
would something like this work? @Edyxia 
![image](https://user-images.githubusercontent.com/2764131/159179210-fd0ecc04-653f-4bf0-ac8d-cdd3a6b84c46.png)

**Comment by Edyxia** [comment]
This is perfect!

**Comment by czmathew** [comment]
fixed and deployed
